spring:
  application:
    name: redis-demo
  redis:
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 10000
    database: 0
    sentinel:
      master: redisgroup
      nodes: 192.168.100.21:7001,192.168.100.21:7002,192.168.100.21:7003
    password: 123456
server:
  port: 10001